name: manning_live
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^0.1.6+1
  auto_size_text: ^1.0.0
  card_settings: ^1.4.1
  cloud_firestore: ^0.12.9
  incrementally_loading_listview: 0.2.0+1
  intl: ^0.15.8
  firebase_auth: ^0.14.0+5
  firebase_remote_config: ^0.2.0+7
  flutter_colorpicker: ^0.2.6
  flutter_cupertino_settings:
    git:
      url: https://github.com/AppleEducate/flutter_cupertino_settings
  flutter_facebook_login: ^2.0.1
  flutter_masked_text: ^0.7.0
  flutter_mobx: ^0.3.0+1
  flutter_signin_button: ^0.3.0
  flutter_statusbarcolor: 0.2.1
  flutter_swiper : ^1.1.6
  flutter_twitter_login: ^1.1.0
  font_awesome_flutter: ^8.5.0
  google_sign_in: ^4.0.7
  html_unescape: 1.0.1+3
  mobx: ^0.3.5
  provider: ^3.0.0+1
  share: ^0.6.2
  shared_preferences: ^0.5.3+4
  timeago: ^2.0.18

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  mobx_codegen: 0.3.3+1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Prata
      fonts:
        - asset: fonts/Prata-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf 
          weight: 200
        - asset: fonts/Montserrat-Light.ttf 
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf 
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf 
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Black.ttf 
          weight: 900
    - family: Passion One
      fonts:
        - asset: fonts/PassionOne-Regular.ttf
        - asset: fonts/PassionOne-Bold.ttf
    - family: Fredoka One
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900
  assets:
    - assets/google_signin_buttons/web/2x/btn_google_signin_light_focus_web@2x.png
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/icons/twitter.png
    - assets/icons/github.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
